# CLIP AST Few Shot
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 16
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

# For Stage 2 training
OPTIM:
  NAME: "adamw"
  LR: 1e-5
  WEIGHT_DECAY: 1e-4
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "CLIPAST"
  
# CLIP-AST specific parameters
RANDOM_SELECTION: False
RANDOM_SEED: 42
STAGE1_EPOCHS: 1
K: 6  # Top-K parameters per transformer block
EVAL_FREQ: 5
LMBD: [0.5, 0.5, 1.0]  # [img_l1, txt_l1, kl] weights for SCL losses
DEVICE: "cuda:0"  # Device to use (cuda:0, cuda:1, cpu, etc.)
    